config/routes.rb
Myapp::Application.routes.draw do
  resources :sales
  resources :days_goals
  resources :salesmen
  resources :sales_goals
  resources :stores
  devise_for :users, :controllers => {registrations: "registrations"}
  get "home/index"
  get "home/minor"
  root to: 'home#index'
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :user_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true, class: 'form-horizontal') do |form| %>
      <div class="form-group <%= store.errors[:name].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Nome da Loja:</label>
      <div class="col-sm-10">
        <%= form.text_field :name, class: 'form-control' %>
        <% if store.errors[:name].any? %>
          <span class="help-block m-b-none font-bold"><%= store.errors[:name].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= store.errors[:user_id].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Proprietário:</label>
      <div class="col-sm-10">
        <%= form.text_field :user_id, class: 'form-control' %>
        <% if store.errors[:user_id].any? %>
          <span class="help-block m-b-none font-bold"><%= store.errors[:user_id].first %></span>
        <% end %>
      </div>
    </div>
    <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <%= link_to 'Cancelar', stores_path, :class => 'btn btn-white' %>
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/stores/_header.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Lojas</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
      </li>
      <li class="active">
        <strong>Lojas</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/stores/edit.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>&nbsp;Editando Loja</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', store: @store %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Lojas</h5>
          <div class="ibox-tools">
          </div>
        </div>
        <div class="ibox-content-scaffold">
          <table class="table table-striped table-hover table-results">
            <thead>
              <tr>
                <th>Nome da Loja</th>
                <th>Proprietário</th>
                <th class="col-sm-3">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @stores.each do |store| %>
                <tr>
                  <td><%= store.name %></td>
                  <td><%= store.user.name %></td>
                <td>
                    <%= link_to fa_icon('eye'),  store, class: 'btn btn-sm btn-success' %>
                    <%= link_to fa_icon('edit'), edit_store_path(store), class: 'btn btn-sm btn-warning' %>
                    <%= link_to fa_icon('trash'), store, method: :delete, data: { confirm: I18n.t('app.messages.are_you_sure') }, class: 'btn btn-sm btn-danger' %>
                </td>
                </tr>
              <% end %>
            </tbody>
            <tfoot>
              <tr>
                <td>
                  <%= link_to fa_icon('plus'), new_store_path, class: 'btn btn-md btn-primary' %></td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $('.table-results').DataTable({
            pageLength: 10,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'PCE'},
                {extend: 'pdf', title: 'PCE'},

                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
              "sEmptyTable": "Nenhum registro encontrado",
              "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
              "sInfoFiltered": "(Filtrados de _MAX_ registros)",
              "sInfoPostFix": "",
              "sInfoThousands": ".",
              "sLengthMenu": "_MENU_ resultados por página",
              "sLoadingRecords": "Carregando...",
              "sProcessing": "Processando...",
              "sZeroRecords": "Nenhum registro encontrado",
              "sSearch": "Pesquisar",
              "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
              },
              "oAria":{
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
              },
              "buttons": {
                "copy": "Copiar",
                "print": "Imprimir"
                              }
            }
        });
    });
  </script>
<% end %>

app/views/stores/new.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nova Loja</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', store: @store %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Mostrando Lojas</h5>
        </div>
        <div class="ibox-content-scaffold">
            <form class="form-horizontal">
              <div class="form-group"><label class="col-sm-2 control-label">Nome da Loja:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @store.name %>
                    </p>
                  </div>
                </div>
              <div class="form-group"><label class="col-sm-2 control-label">Proprietário:</label>
                <div class="col-sm-10">
                  <p style="color:#565555;" class="form-control-static">
                    <%= @store.user %>
                    </p>
                  </div>
                </div>
              <div class="hr-line-dashed">
              </div>
                <div class="form-group">
                  <div class="col-sm-4">
                      <%= link_to 'Voltar', stores_path, :class => 'btn btn-white' %>
                      <%= link_to 'Editar', edit_store_path(@store), :class => "btn btn-primary" %>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>