config/routes.rb
Myapp::Application.routes.draw do
  resources :sales
  resources :days_goals
  resources :salesmen
  resources :sales_goals
  resources :stores
  devise_for :users, :controllers => {registrations: "registrations"}
  get "home/index"
  get "home/minor"
  root to: 'home#index'
end

app/models/days_goal.rb
class DaysGoal < ApplicationRecord
  belongs_to :sales_goals
end

app/controllers/days_goals_controller.rb
class DaysGoalsController < ApplicationController
  before_action :set_days_goal, only: [:show, :edit, :update, :destroy]

  # GET /days_goals
  # GET /days_goals.json
  def index
    @days_goals = DaysGoal.all
  end

  # GET /days_goals/1
  # GET /days_goals/1.json
  def show
  end

  # GET /days_goals/new
  def new
    @days_goal = DaysGoal.new
  end

  # GET /days_goals/1/edit
  def edit
  end

  # POST /days_goals
  # POST /days_goals.json
  def create
    @days_goal = DaysGoal.new(days_goal_params)

    respond_to do |format|
      if @days_goal.save
        format.html { redirect_to @days_goal, notice: 'Days goal was successfully created.' }
        format.json { render :show, status: :created, location: @days_goal }
      else
        format.html { render :new }
        format.json { render json: @days_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days_goals/1
  # PATCH/PUT /days_goals/1.json
  def update
    respond_to do |format|
      if @days_goal.update(days_goal_params)
        format.html { redirect_to @days_goal, notice: 'Days goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @days_goal }
      else
        format.html { render :edit }
        format.json { render json: @days_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days_goals/1
  # DELETE /days_goals/1.json
  def destroy
    @days_goal.destroy
    respond_to do |format|
      format.html { redirect_to days_goals_url, notice: 'Days goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_days_goal
      @days_goal = DaysGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def days_goal_params
      params.require(:days_goal).permit(:sales_goals_id, :date_sales, :value)
    end
end

app/helpers/days_goals_helper.rb
module DaysGoalsHelper
end

app/views/days_goals/_form.html.erb
<%= form_with(model: days_goal, local: true, class: 'form-horizontal') do |form| %>
      <div class="form-group <%= days_goal.errors[:sales_goals_id].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Meta:</label>
      <div class="col-sm-10">
        <%= form.text_field :sales_goals_id, class: 'form-control' %>
        <% if days_goal.errors[:sales_goals_id].any? %>
          <span class="help-block m-b-none font-bold"><%= days_goal.errors[:sales_goals_id].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= days_goal.errors[:date_sales].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Data:</label>
      <div class="col-sm-10">
        <%= form.date_select :date_sales, class: 'form-control' %>
        <% if days_goal.errors[:date_sales].any? %>
          <span class="help-block m-b-none font-bold"><%= days_goal.errors[:date_sales].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= days_goal.errors[:value].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Valor:</label>
      <div class="col-sm-10">
        <%= form.text_field :value, class: 'form-control' %>
        <% if days_goal.errors[:value].any? %>
          <span class="help-block m-b-none font-bold"><%= days_goal.errors[:value].first %></span>
        <% end %>
      </div>
    </div>
    <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <%= link_to 'Cancelar', days_goals_path, :class => 'btn btn-white' %>
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/days_goals/_header.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Dia das Metas</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
      </li>
      <li class="active">
        <strong>Dia das Metas</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/days_goals/edit.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>&nbsp;Editando dia da Meta</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', days_goal: @days_goal %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/days_goals/index.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Dias das Metas</h5>
          <div class="ibox-tools">
            <a class="collapse-link">
              <i class="fa fa-chevron-up"></i>
            </a>
          </div>
        </div>
        <div class="ibox-content-scaffold">
          <table class="table table-striped table-hover table-results">
            <thead>
              <tr>
                <th>Metas</th>
                <th>Data da Meta</th>
                <th>Valor</th>
                <th class="col-sm-3">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @days_goals.each do |days_goal| %>
                <tr>
                  <td><%= days_goal.sales_goals %></td>
                  <td><%= days_goal.date_sales %></td>
                  <td><%= days_goal.value %></td>
                  <td>
                    <%= link_to fa_icon('eye'),  days_goal, class: 'btn btn-sm btn-success' %>
                    <%= link_to fa_icon('edit'), edit_days_goal_path(days_goal), class: 'btn btn-sm btn-warning' %>
                    <%= link_to fa_icon('trash'), days_goal, method: :delete, data: { confirm: I18n.t('app.messages.are_you_sure') }, class: 'btn btn-sm btn-danger' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
            <tfoot>
              <tr>
                <td>
                  <%= link_to fa_icon('plus'), new_days_goal_path, class: 'btn btn-md btn-primary' %></td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $('.table-results').DataTable({
            pageLength: 10,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'PCE'},
                {extend: 'pdf', title: 'PCE'},

                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
              "sEmptyTable": "Nenhum registro encontrado",
              "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
              "sInfoFiltered": "(Filtrados de _MAX_ registros)",
              "sInfoPostFix": "",
              "sInfoThousands": ".",
              "sLengthMenu": "_MENU_ resultados por página",
              "sLoadingRecords": "Carregando...",
              "sProcessing": "Processando...",
              "sZeroRecords": "Nenhum registro encontrado",
              "sSearch": "Pesquisar",
              "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
              },
              "oAria":{
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
              },
              "buttons": {
                "copy": "Copiar",
                "print": "Imprimir"
                              }
            }
        });
    });
  </script>
<% end %>

app/views/days_goals/new.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Novo dia de Metas</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', days_goal: @days_goal %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/days_goals/show.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Mostrando Meta</h5>
        </div>
        <div class="ibox-content-scaffold">
            <form class="form-horizontal">
              <div class="form-group"><label class="col-sm-2 control-label">Meta:</label>
                <div class="col-sm-10">
                  <p style="color:#565555;" class="form-control-static">
                      <%= @days_goal.sales_goals %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Data da Meta:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @days_goal.date_sales %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Valor:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @days_goal.value %>
                    </p>
                  </div>
                </div>
              <div class="hr-line-dashed">
              </div>
              <div class="form-group">
                  <div class="col-sm-4">
                      <%= link_to 'Voltar', days_goals_path, :class => 'btn btn-white' %>
                      <%= link_to 'Editar', edit_days_goal_path(@days_goal), :class => "btn btn-primary" %>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>