config/routes.rb
Myapp::Application.routes.draw do
  resources :sales
  resources :days_goals
  resources :salesmen
  resources :sales_goals
  resources :stores
  devise_for :users, :controllers => {registrations: "registrations"}
  get "home/index"
  get "home/minor"
  root to: 'home#index'
end

app/models/sales_goal.rb
class SalesGoal < ApplicationRecord
end

app/controllers/sales_goals_controller.rb
class SalesGoalsController < ApplicationController
  before_action :set_sales_goal, only: [:show, :edit, :update, :destroy]

  # GET /sales_goals
  # GET /sales_goals.json
  def index
    @sales_goals = SalesGoal.all
  end

  # GET /sales_goals/1
  # GET /sales_goals/1.json
  def show
  end

  # GET /sales_goals/new
  def new
    @sales_goal = SalesGoal.new
  end

  # GET /sales_goals/1/edit
  def edit
  end

  # POST /sales_goals
  # POST /sales_goals.json
  def create
    @sales_goal = SalesGoal.new(sales_goal_params)

    respond_to do |format|
      if @sales_goal.save
        format.html { redirect_to @sales_goal, notice: 'Sales goal was successfully created.' }
        format.json { render :show, status: :created, location: @sales_goal }
      else
        format.html { render :new }
        format.json { render json: @sales_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_goals/1
  # PATCH/PUT /sales_goals/1.json
  def update
    respond_to do |format|
      if @sales_goal.update(sales_goal_params)
        format.html { redirect_to @sales_goal, notice: 'Sales goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_goal }
      else
        format.html { render :edit }
        format.json { render json: @sales_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_goals/1
  # DELETE /sales_goals/1.json
  def destroy
    @sales_goal.destroy
    respond_to do |format|
      format.html { redirect_to sales_goals_url, notice: 'Sales goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_goal
      @sales_goal = SalesGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_goal_params
      params.require(:sales_goal).permit(:dt_start, :dt_end, :ref_month, :value)
    end
end

app/helpers/sales_goals_helper.rb
module SalesGoalsHelper
end

app/views/sales_goals/_form.html.erb
<%= form_with(model: sales_goal, local: true, class: 'form-horizontal') do |form| %>
      <div class="form-group <%= sales_goal.errors[:dt_start].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Data Inicial:</label>
      <div class="col-sm-10">
        <%= form.date_select :dt_start, class: 'form-control' %>
        <% if sales_goal.errors[:dt_start].any? %>
          <span class="help-block m-b-none font-bold"><%= sales_goal.errors[:dt_start].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= sales_goal.errors[:dt_end].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Data Final:</label>
      <div class="col-sm-10">
        <%= form.date_select :dt_end, class: 'form-control' %>
        <% if sales_goal.errors[:dt_end].any? %>
          <span class="help-block m-b-none font-bold"><%= sales_goal.errors[:dt_end].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= sales_goal.errors[:ref_month].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Mês de Referência:</label>
      <div class="col-sm-10">
        <%= form.date_select :ref_month, class: 'form-control' %>
        <% if sales_goal.errors[:ref_month].any? %>
          <span class="help-block m-b-none font-bold"><%= sales_goal.errors[:ref_month].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= sales_goal.errors[:value].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Valor:</label>
      <div class="col-sm-10">
        <%= form.text_field :value, class: 'form-control' %>
        <% if sales_goal.errors[:value].any? %>
          <span class="help-block m-b-none font-bold"><%= sales_goal.errors[:value].first %></span>
        <% end %>
      </div>
    </div>
    <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <%= link_to 'Cancelar', sales_goals_path, :class => 'btn btn-white' %>
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/sales_goals/_header.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Metas</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
      </li>
      <li class="active">
        <strong>Metas</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/sales_goals/edit.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>&nbsp;Editando Metas</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', sales_goal: @sales_goal %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sales_goals/index.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Metas dos Vendedores</h5>
          <div class="ibox-tools">
          </div>
        </div>
        <div class="ibox-content-scaffold">
          <table class="table table-striped table-hover table-results">
            <thead>
              <tr>
                <th>Data de Início</th>
                <th>Data Final</th>
                <th>Mês de referência</th>
                <th>Valor</th>
                <th class="col-sm-3">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @sales_goals.each do |sales_goal| %>
                <tr>
                  <td><%= sales_goal.dt_start %></td>
                  <td><%= sales_goal.dt_end %></td>
                  <td><%= sales_goal.ref_month %></td>
                  <td><%= sales_goal.value %></td>
                  <td>
                    <%= link_to fa_icon('eye'),  sales_goal, class: 'btn btn-sm btn-success' %>
                    <%= link_to fa_icon('edit'), edit_sales_goal_path(sales_goal), class: 'btn btn-sm btn-warning' %>
                    <%= link_to fa_icon('trash'), sales_goal, method: :delete, data: { confirm: I18n.t('app.messages.are_you_sure') }, class: 'btn btn-sm btn-danger' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
            <tfoot>
              <tr>
                <td>
                  <%= link_to fa_icon('plus'), new_sales_goal_path, class: 'btn btn-md btn-primary' %></td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $('.table-results').DataTable({
            pageLength: 10,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'PCE'},
                {extend: 'pdf', title: 'PCE'},

                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
              "sEmptyTable": "Nenhum registro encontrado",
              "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
              "sInfoFiltered": "(Filtrados de _MAX_ registros)",
              "sInfoPostFix": "",
              "sInfoThousands": ".",
              "sLengthMenu": "_MENU_ resultados por página",
              "sLoadingRecords": "Carregando...",
              "sProcessing": "Processando...",
              "sZeroRecords": "Nenhum registro encontrado",
              "sSearch": "Pesquisar",
              "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
              },
              "oAria":{
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
              },
              "buttons": {
                "copy": "Copiar",
                "print": "Imprimir"
                              }
            }
        });
    });
  </script>
<% end %>

app/views/sales_goals/new.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nova Meta</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', sales_goal: @sales_goal %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sales_goals/show.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Mostrando Meta</h5>
        </div>
        <div class="ibox-content-scaffold">
            <form class="form-horizontal">
                <div class="form-group"><label class="col-sm-2 control-label">Data Inicial:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sales_goal.dt_start %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Data Final:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sales_goal.dt_end %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Mês de Referência:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sales_goal.ref_month %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Valor</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sales_goal.value %>
                    </p>
                  </div>
                </div>
              <div class="hr-line-dashed">
              </div>
              <div class="form-group">
                  <div class="col-sm-4">
                      <%= link_to 'Voltar', sales_goals_path, :class => 'btn btn-white' %>
                      <%= link_to 'Editar', edit_sales_goal_path(@sales_goal), :class => "btn btn-primary" %>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>