config/routes.rb
Myapp::Application.routes.draw do
  resources :sales
  resources :days_goals
  resources :salesmen
  resources :sales_goals
  resources :stores
  devise_for :users, :controllers => {registrations: "registrations"}
  get "home/index"
  get "home/minor"
  root to: 'home#index'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :day_goals
  belongs_to :salesman
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:day_goals_id, :value, :salesman_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true, class: 'form-horizontal') do |form| %>
      <div class="form-group <%= sale.errors[:day_goals_id].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Meta do dia:</label>
      <div class="col-sm-10">
        <%= form.text_field :day_goals_id, class: 'form-control' %>
        <% if sale.errors[:day_goals_id].any? %>
          <span class="help-block m-b-none font-bold"><%= sale.errors[:day_goals_id].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= sale.errors[:value].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Valor:</label>
      <div class="col-sm-10">
        <%= form.text_field :value, class: 'form-control' %>
        <% if sale.errors[:value].any? %>
          <span class="help-block m-b-none font-bold"><%= sale.errors[:value].first %></span>
        <% end %>
      </div>
    </div>
      <div class="form-group <%= sale.errors[:salesman_id].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Vendendor:</label>
      <div class="col-sm-10">
        <%= form.text_field :salesman_id, class: 'form-control' %>
        <% if sale.errors[:salesman_id].any? %>
          <span class="help-block m-b-none font-bold"><%= sale.errors[:salesman_id].first %></span>
        <% end %>
      </div>
    </div>
    <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <%= link_to 'Cancelar', sales_path, :class => 'btn btn-white' %>
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/sales/_header.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Vendas</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
      </li>
      <li class="active">
        <strong>Venda</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/sales/edit.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>&nbsp;Editando Venda</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', sale: @sale %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sales/index.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Vendas</h5>
          <div class="ibox-tools">
          </div>
        </div>
        <div class="ibox-content-scaffold">
          <table class="table table-striped table-hover table-results">
            <thead>
              <tr>
                <th>Meta do dia</th>
                <th>Valor</th>
                <th>Vendedor</th>
                <th class="col-sm-3">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @sales.each do |sale| %>
                <tr>
                  <td><%= sale.day_goals %></td>
                  <td><%= sale.value %></td>
                  <td><%= sale.salesman %></td>
                  <td>
                    <%= link_to fa_icon('eye'),  sale, class: 'btn btn-sm btn-success' %>
                    <%= link_to fa_icon('edit'), edit_sale_path(sale), class: 'btn btn-sm btn-warning' %>
                    <%= link_to fa_icon('trash'), sale, method: :delete, data: { confirm: I18n.t('app.messages.are_you_sure') }, class: 'btn btn-sm btn-danger' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
            <tfoot>
              <tr>
                <td>
                  <%= link_to fa_icon('plus'), new_sale_path, class: 'btn btn-md btn-primary' %></td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $('.table-results').DataTable({
            pageLength: 10,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'PCE'},
                {extend: 'pdf', title: 'PCE'},

                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
              "sEmptyTable": "Nenhum registro encontrado",
              "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
              "sInfoFiltered": "(Filtrados de _MAX_ registros)",
              "sInfoPostFix": "",
              "sInfoThousands": ".",
              "sLengthMenu": "_MENU_ resultados por página",
              "sLoadingRecords": "Carregando...",
              "sProcessing": "Processando...",
              "sZeroRecords": "Nenhum registro encontrado",
              "sSearch": "Pesquisar",
              "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
              },
              "oAria":{
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
              },
              "buttons": {
                "copy": "Copiar",
                "print": "Imprimir"
                              }
            }
        });
    });
  </script>
<% end %>

app/views/sales/new.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nova Venda</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', sale: @sale %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sales/show.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Mostrando sale</h5>
        </div>
        <div class="ibox-content">
            <form class="form-horizontal">
              <div class="form-group"><label class="col-sm-2 control-label">Day goals</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sale.day_goals %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Value</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sale.value %>
                    </p>
                  </div>
                </div>
                <div class="form-group"><label class="col-sm-2 control-label">Salesman</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control-static">
                      <%= @sale.salesman %>
                    </p>
                  </div>
                </div>
              <div class="hr-line-dashed">
              </div>
              <div class="form-group">
                  <div class="col-sm-4">
                      <%= link_to 'Voltar', sales_path, :class => 'btn btn-white' %>
                      <%= link_to 'Editar', edit_sale_path(@sale), :class => "btn btn-primary" %>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>